name: Docker Build & Scan (production)

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  build_scan_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- Build and Scan API Image ---
      - name: Build API Docker image (no push yet)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.prod # Your production Dockerfile for API
          tags: portfolio_api:latest # Tag for local use in the workflow
          outputs: type=docker # Output as a local Docker image for scanning
          push: false # Do not push yet

      - name: Scan API Image with Trivy
        uses: aquasecurity/trivy-action@master # Use the latest version or a specific tag
        with:
          image-ref: portfolio_api:latest # Scan the locally built image
          format: 'table' # Output format (table, json, sarif, etc.)
          severity: 'HIGH,CRITICAL' # Report High and Critical vulnerabilities
          exit-code: '1' # Fail the GitHub Action job if vulns of specified severity are found
          ignore-unfixed: true 

      - name: Push API Docker image
        # This step will only run if the Trivy scan step did NOT fail (exit-code 0)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.prod # Your production Dockerfile for API
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/portfolio_api:latest 
            ${{ secrets.DOCKERHUB_USERNAME }}/portfolio_api:${{ github.run_number }}
          push: true # Now push the image

      # --- Build and Scan Frontend Image ---
      - name: Build Frontend Docker image (no push yet)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.frontend 
          tags: portfolio_frontend:latest # Tag for local use in the workflow
          outputs: type=docker # Output as a local Docker image for scanning
          push: false 

      - name: Scan Frontend Image with Trivy
        uses: aquasecurity/trivy-action@master # Use the latest version or a specific tag
        with:
          image-ref: portfolio_frontend:latest # Scan the locally built image
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '1' # Fail the GitHub Action job if vulns of specified severity are found
          ignore-unfixed: true # Only show vulnerabilities with fixes

      - name: Push Frontend Docker image
        # This step will only run if the Trivy scan step did NOT fail (exit-code 0)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.frontend # Your Dockerfile for Frontend
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/portfolio_frontend:latest 
            ${{ secrets.DOCKERHUB_USERNAME }}/portfolio_frontend:${{ github.run_number }}
          push: true # Now push the image